# Generated by Django 5.2.7 on 2025-10-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_alter_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.telegramuser')),
            ],
        ),
    ]
